/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <glade/glade.h>

int configuration_modified = 2;

static int
__handle_cancel (GladeXML *xml)
{
	if (configuration_modified) {
		return 1;
	} else {
		return 1;
	}
}

static int
__handle_confirm (GladeXML *xml)
{
	return 1;
}

static int
__handle_help (GladeXML *xml)
{
	return 1;
}

int
main (int argc, char *argv[])
{
	GladeXML *xml;
	GtkWidget *conf_dialog;
	int response, quit;

#ifdef ENABLE_NLS
	bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
#endif

	gtk_set_locale ();
	gtk_init (&argc, &argv);

	/* Init our mem_handler */
	mem_handler_init();

	/* contruct and show main window */
	xml = glade_xml_new ("data/backup-manager-preferences.glade", NULL, NULL);
	glade_xml_signal_autoconnect (xml);
	conf_dialog = glade_xml_get_widget (xml, "configuration_dialog");

	quit = 0;
	while (!quit) {
		response = gtk_dialog_run (GTK_DIALOG (conf_dialog));

		switch (response) {
			case GTK_RESPONSE_OK:
				/* check and save conf */
				quit = __handle_confirm (xml);
				break;
			case GTK_RESPONSE_CANCEL:
				/* confirm and discard */
				quit = __handle_confirm (xml);
				break;
			case GTK_RESPONSE_HELP:
				/* launch help : unimplemented */
				quit = __handle_help (xml);
				break;
			default:
				g_assert_not_reached ();
		}
	}
	
	gtk_widget_destroy (conf_dialog);
	
	g_object_unref (G_OBJECT (xml));
	
	return 0;
}

