/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "bm.h";

#include "global_widgets.h"

int
main (int argc, char *argv[])
{
  
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /* Init our mem_handler */
  mem_handler_init();

  /* Some stuff to do with our objects */
  configuration_window = create_configuration_window();
  gtk_widget_show(configuration_window);
  
  filechooser = create_filechooser(); 
  
  /* test */
  bm_load_conf("/etc/backup-manager.conf"); 

  mem_print_status();
  
  gtk_main ();
  
  mem_print_status();
  return 0;
}

