/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <glade/glade.h>

#include "support.h"

int
main (int argc, char *argv[])
{
	GladeXML *xml;

#ifdef ENABLE_NLS
	bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
#endif

	gtk_set_locale ();
	gtk_init (&argc, &argv);

	add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

	/* Init our mem_handler */
	mem_handler_init();

	/* contruct and show main window */
	xml = glade_xml_new ("data/backup-manager-preferences.glade", NULL, NULL);
	glade_xml_signal_autoconnect (xml);
	
	gtk_main ();
	
	return 0;
}

